name: Deploy React Frontend to S3

on:
  push:
    branches:
      - main  # Runs when pushing to `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install
        working-directory: client  # Adjust this if your frontend is in another folder

      - name: Build React App
        run: npm run build
        working-directory: client

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1  # Change to your AWS region
        SOURCE_DIR: client/build  # Adjust if your frontend folder is different
        DEST_DIR: s3://electromagnet-bucket

