name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ELECTROMAGNET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ELECTROMAGNET_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      # Install dependencies and build the React app
      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build
      
      # Debugging step to check if the build was successful
      - name: Debug Secrets
        run: echo "S3 Bucket is $AWS_S3_BUCKET"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      # Deploy to S3
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.0  # Changed version to v0.5.0
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ELECTROMAGNET_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ELECTROMAGNET_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Change to your AWS region
          SOURCE_DIR: './client/build'  # Path to the build directory
          
